USE MOVIESDB;
DROP TABLE MOVIES;
CREATE TABLE MOVIES(MOVIEID BIGINT,TITLE VARCHAR(255),GENRES LONGTEXT);
CREATE TABLE RATINGS(USERID BIGINT,MOVIEID BIGINT,TIMESTAMP BIGINT,RATING SMALLINT);
CREATE TABLE TAGS(USERID BIGINT,MOVIEID BIGINT,TIMESTAMP BIGINT,TAG VARCHAR(255));
CREATE TABLE LINKS(IMDBID BIGINT,MOVIEID BIGINT,TMDBID BIGINT);
CREATE TABLE GENOME_TAGS(TAGID BIGINT,TAG VARCHAR(255));
CREATE TABLE GENOME_SCORES(MOVIEID BIGINT,TAGID BIGINT, RELEVANCE DECIMAL(65,30));